export const START_GET_LIST = "START_GET_LIST";
export const SUCCESS_GET_LIST = "SUCCESS_GET_LIST";
export const FAIL_GET_LIST = "FAIL_GET_LIST";

export const START_GET_STREAMING = "START_GET_STREAMING";
export const SUCCESS_GET_STREAMING = "SUCCESS_GET_STREAMING";
export const FAIL_GET_STREAMING = "FAIL_GET_STREAMING";

export const CLEAR_MOVIE = "CLEAR_MOVIE";
export const START_GET_MOVIE_BY_ID = "START_GET_MOVIE_BY_ID";
export const SUCCESS_GET_MOVIE_BY_ID = "SUCCESS_GET_MOVIE_BY_ID";
export const FAIL_GET_MOVIE_BY_ID = "FAIL_GET_MOVIE_BY_ID";

export const GET_ALL_LISTS = "GET_ALL_LISTS";
